#服务配置
server:
  port: 8092
  servlet:
    context-path: /
    session:
      timeout: 1800
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  shutdown: graceful

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initSize: 1
    maxSize: 10
    minSize: 1
    password: nvb
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://43.138.65.234:31477/november?useSSL=false&servertimezone=utc&autoReconnect=true&characterEncoding=utf-8
    username: nvb
    schema: classpath:schema.sql
#    data: classpath:data.sql
    sql-script-encoding: utf-8
    initialization-mode: always

  mapper:
    acquireRetryAttempts: 10
    acquireRetryDelay: 1000
    breakAfterAcquireFailure: false
    idleConnectionTestPeriod: 60
    path: classpath*:mappers/*.xml
    preferredTestQuery: select 1
    repeat: 30
    testConnectionOnCheckin: false
#  datasource:
#    url: jdbc:mysql://43.138.65.234:31477/november
#    username: nvb
#    password: nvb
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      auto-commit: false
#      connection-timeout: 3000
#      validation-timeout: 3000
#      max-lifetime: 60000
#      maximum-pool-size: 20
#      minimum-idle: 1

